### PR TITLE
Initial cut at cloud computing overview

### PR DESCRIPTION
**Pull request by atombaby**

### CODE REVIEW

**Comment by atombaby** [comment]
@dtenenba @dirkpetersen I took a swipe at this intro page.  Can you take a quick look, let me know if it's good enough to merge so I can delete it?

**Comment by dtenenba** [comment]
Looks good to me. I think the resource that it links to (`/compdemos/awsBatch`) needs some overhauling, but that's probably me. The other thing is that this page may need to change depending on the result of the cloud re-architecture project. But it's accurate in the context of what we have now.

**Comment by sgglick** [comment]
Just to interject, at some point in the near future, FH will have an approved cloud computing security standard. This would be a good place to reference it.  Will provide language when the standard is approved.

**Comment by vortexing** [comment]
Sam wrote the AWS Batch page from his experience but wanted a review from SciComp to make it official.  It needs to be owned by you all for sure, but he gave you the basics to work from, including the introductory material and everything, so it should be easier than starting from scratch.  When/if you want to review the content, you may want to integrate the page Sam wrote into an article and not have it as a demo anymore.  To some degree compdemos written by scientists are more a request for new content from SciComp than final work.

**Comment by atombaby** [comment]
I think Sam's intro to AWS Batch looks really good- maybe @dtenenba would like to look at moving that into the _computing section as it's not really a demo per-se.  All that said, I'd like to get a review on this [file](https://github.com/FredHutch/wiki/blob/a19bbc29e3cb74643b642bf188b1768ce30142eb/_computing/cluster_cloudCompute.md) and get this PR closed.

**Comment by vortexing** [comment]
For some reason it doesn't seem to want to let me review b/c @dtenenba  and @dirkpetersen  were tagged.  But that's better anyway.  I will create an issue about the AWS BAtch materials and let those guys do a review and merge!!

**Pull request merged**
