### PR TITLE
Sgglick patch 2

### PR DESCRIPTION
**Pull request by vortexing**

### CODE REVIEW

**Comment by vortexing** [comment]
@Rachierizz and @sgglick Did you come to a conclusion about this pull request re: Caisis requests?

**Comment by vortexing** [comment]
That merged all of the changes in master since you made your original branch into your branch.  You need to commit YOUR edits to your branch.

**Comment by vortexing** [comment]
Like that?

**Comment by sgglick** [comment]
Amy,   the change is really minor.. Also, I notice on of the links in that language which I thought was to the extranet is actually requiring credentials.  So go ahead and merge.  Tomorrow I will 1: create a new branch 2: make the last two changes 3) make a pull request and then you can merge.

I owe you some cookies...at least for the kids.

Susan

**Pull request merged**
