### PR TITLE
Nextflow FAQ

### PR DESCRIPTION
**Pull request by eharkins**
@sminot and I have added some "gotchas", FAQ, and more info to the nextflow docs. Hopefully we can set up a system where folks fork and PR changes to this doc when they have generally applicable nextflow solutions that others can benefit from here at the Hutch. That way people aren't running into the same issues as much or doing as much re-asking of questions in the nextflow channel on slack.

### CODE REVIEW

**Comment by dtenenba** [comment]
This looks really good. Wondering if it would be good to mention [Tower](https://tower.nf).
Guessing most potential Nextflow users would appreciate the UI showing their jobs' status.

**Comment by eharkins** [comment]
Good idea @dtenenba! I haven't used it, would you like to add something about if you have?

**Comment by sminot** [comment]
I have used Tower and I can add some text. Great idea @dtenenba!

**Comment by sminot** [comment]
Ok, just added some text describing Tower, @dtenenba

**Comment by dtenenba** [comment]
@sminot be sure and mention how to actually invoke tower. Don't you have to submit your job with a `-with-tower` flag or something?

**Comment by sminot** [comment]
That's actually taken care of with the additions to the config file, as they describe it on the Tower website

**Comment by dtenenba** [comment]
OK, nice!  So that probably turns on tower logging for all jobs. I can imagine you might want to turn it off sometimes so it might be good to discuss how to do that. But that's not a big deal, so I will go ahead and merge this.

**Pull request merged**
