### PR TITLE
More tips and hints on jobs and job management

### PR DESCRIPTION
**Pull request by atombaby**
Two biggies here- one on prioritizing jobs, another on monitoring job resource utilization.

### CODE REVIEW

**Comment by vortexing** [comment]
This branch seems to have conflicts with the main branch for some reason.  Also needs a review from @FredHutch/scicomp 

Shall we get this moving/fixed?

**Comment by atombaby** [comment]
I've merged main back into this branch- seems OK in my checkout currently.  The old conflicts may have been due to this PR being based on master, not main.

**Review by scottsisco — CHANGES_REQUESTED** [review]
I am a little confused by line 161. jobs can only be **nicer-**  should it be the jobs can only be **niced**?

**Comment by atombaby** [comment]
Yeah, both "niced" and "nicer" are little jargon-y and not real clear to non-Unix folks.  Removed it, it's good enough without that phrase.

**Review by scottsisco — APPROVED** [review]
Looks good.

**Pull request merged**
