### PR TITLE
Formatting repair on access_credentials.md

### PR DESCRIPTION
**Pull request by vortexing**
Minimal edits, no content change, just formatting

### CODE REVIEW

**Comment by dtenenba** [comment]
You should specify how to contact scicomp. If a person is new enough to not know how to get on a rhino, then they will not know how to contact scicomp. So it should explicitly say "email scicomp@fredhutch.org".

**Comment by dtenenba** [comment]
@vortexing  You are right and I'd forgotten about this. 
Maybe we could just say "email scicomp@" and leave out the domain name. 
When I type "scicomp@" into my mail client, an autocompletion suggestion comes up with the full address. So that's probably enough.

**Comment by vortexing** [comment]
Will writing username@ actually avoid the robots???  I like that convention too.  It's totally doable!!  Maybe we should try to change over?

**Comment by dtenenba** [comment]
I'm worried that `address@` will be too easy for spammers to harvest. All they have to do is add the domain name that the page is on. I think we've hit the sweet spot the way it is.

**Comment by vortexing** [comment]
OK sounds good.  Let's just fumble through here and then if we can add some sort of info for people somehow via a hover or something then we will!!

**Comment by dtenenba** [comment]
Any content of a hover/tooltip can also be harvested. ;-(

**Pull request merged**
