### PR TITLE
how to rhino quick tune up.

### LINKED ISSUE #574: How to Rhino navigation
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://sciwiki.fredhutch.org/compdemos/howtoRhino/

### Specific information requests or concerns, or specific region on page of content to refresh.
"on this page" doesn't seem to match the headers; "rhino Compute Nodes" isn't represented as a category but the subheadings are? It would be great to clarify this page

### PR DESCRIPTION
**Pull request by vortexing**
Trying to fix the formatting and clean things up a bit (let's have how to rhino not talk about gizmo!!!). Hopefully closes #574 .

### CODE REVIEW

**Review by k8hertweck — COMMENTED** [review]
I thought How to Rhino was going away? I think I'm glad it's not?

Anyway, this is great, though the sections on X on the How to Rhino page are confusing. In particular:
- [this section](https://github.com/FredHutch/wiki/blob/cfb70c056a1b09537ee612ec03da09ee7544daf7/_compdemos/howtoRhino.md#macos) and the one that follows references links that don't seem to exist? 
- The section for Everyone below that seems like it should go first, since access info doesn't matter if you don't know what it is
- Why is there a separate section for X Notes, when it could either go higher up with the basic X info, or down below with the tips/tricks/gotchas?

I'd be happy to tackle these issues, either here or in a separate PR

**Comment by vortexing** [comment]
Yeah, clean it up in this PR.  I took a stab at cleaning but didn't do a thorough enough clean job.  I was mostly going through looking for beagle and koshu stuff so tried to split off these tiny edits over into a separate PR.  But that lack of rhino focus shows.  So make it pretty!  This will be the home for all detailed Rhino info beyond your other "How to log on the first time" doc, so no limit as to how detailed to get here.

**Comment by k8hertweck** [comment]
MAKE IT PRETTY and FULLY DOCUMENT are like catnip to me. I assigned myself to remind myself to do it.

**Comment by vortexing** [comment]
If no one has any blocking thoughts here, I'd like to merge this today during the Wiki-hour and then future work can be done.

**Pull request merged**
