### PR TITLE
Update clsp_specimenBanking.md

### PR DESCRIPTION
**Pull request by sunilayala**
Can we also rename the link in the left fork to "Specimen Data Management System" instead of "Specimen Banking"?

I also want to embed a PDF/attach a link to a PDF where it says "Refer to the Key Features of the application here". Can you help me do this please? 

I tried to follow the syntax for showing the image screenshot of a youtube video in the documentation ([The Gift of Time](https://youtu.be/rN7cmb1K2yA "Click to see The Gift of Time"))  - I can't see the image screenshot in the Preview, can you please check if I've done this correctly? The video I want to embed is at https://www.youtube.com/watch?v=pEN1P3PL4xs

Thank you!
Sunil Ayalasomayajula

### CODE REVIEW

**Comment by vortexing** [comment]
I can help with the sidebar issues, as well as get your pdf linked up and your youtube video as well.  

WRT to your edits, it would be better if you could provide some bullet points or some information about the features of the tool in this document in line.  That will help people find your content via the search tool whereas just putting in a pdf will not be searchable.  Please add at least a portion of the text in the pdf into the markdown file, ideally the chunks that have the keywords that you'd anticipate folks searching for that would lead them to your page.

**Comment by sunilayala** [comment]
> Also, "Specimen Data Management System" is too long for the sidebar. Would you be ok with "Specimen Data Management" ? Or something even shorter that you can think of?

Specimen Data Management is probably ok. I think people might not understand if we just put in say "Open Specimen"

**Comment by sunilayala** [comment]
> I can help with the sidebar issues, as well as get your pdf linked up and your youtube video as well.
> 
> WRT to your edits, it would be better if you could provide some bullet points or some information about the features of the tool in this document in line. That will help people find your content via the search tool whereas just putting in a pdf will not be searchable. Please add at least a portion of the text in the pdf into the markdown file, ideally the chunks that have the keywords that you'd anticipate folks searching for that would lead them to your page.

Thanks so much! I will email you the PDF.

The key features are actually in the PDF and can probably be extracted and put into the article as well - I can do that right away - please see the PDF that I'm mailing you and please suggest if there is a nice way to format this in the article into mini-sections the way it is in the PDF

**Comment by sunilayala** [comment]
Hi Amy,

I want to attach this PDF at the place where it says “Refer to the Key Features of the application here”

Based on your suggestion, I will extract some of the features and put them into the article – can you please see how they can be formatted nicely so that they stack up well in the display?

Here’s a snapshot of  the features from the document:

***@***.***

Thanks,
Sunil

**Comment by vortexing** [comment]
I can attach the pdf, but please paste in the text to the markdown file and commit your edits.  Then we will do a formatting review prior to merging the pull request to make sure the TOC stacks up like it should.  ;)

**Comment by sunilayala** [comment]
Thanks @vortexing - I have added the key features into the body of the article one after the other under the "Key Features" section - if can format them into a grid or something, that would be great.

**Comment by vortexing** [comment]
Upon further review, I cannot actually edit your PR due to the fact that you forked the repository instead of just making a branch.  So you'll have to actually close this, and move your edits over into a branch of the repo before I can make any edits.  See our editing/contribution instructions here: https://github.com/FredHutch/wiki#general-editing-process

**Comment by sunilayala** [comment]
Closing this as Amy advised "Upon further review, I cannot actually edit your PR due to the fact that you forked the repository instead of just making a branch. So you'll have to actually close this, and move your edits over into a branch of the repo before I can make any edits. "

**Comment by sunilayala** [comment]
Hi Amy,

I have tried to edit the article again and it said it created a new branch this time – I submitted a pull request. Please see if that is ok.

Thanks,
Sunil

**Pull request closed without merging**
