### PR TITLE
update rModules

### PR DESCRIPTION
**Pull request by fizwit**
update R modules, improve section of .libPaths and what could go wrong with installing R libraries on the Rhino.

### CODE REVIEW

**Comment by dtenenba** [comment]
I made a few small changes (formatting mostly).

Do we want to put in a link to https://github.com/FredHutch/easybuild-life-sciences/issues/new to indicate where requests for new libraries should go? My only hesitation is that both the wiki and easybuild-life-sciences are public repos so this may result in noise or requests from non hutch people who don't quite get it....

**Comment by fizwit** [comment]
if we had other documentation about how to open tickets, open issues and visit office hours. The we could just make a reference to center net or some other private source for how to open issues.

**Comment by dtenenba** [comment]
Yeah, that would be good to have, but is beyond the scope of this PR right now, so I will approve it.

**Review by dtenenba — APPROVED** [review]
LGTM

**Pull request merged**
