### PR TITLE
Data visualization content

### PR DESCRIPTION
**Pull request by k8hertweck**
What data viz resources are most used at the Hutch?

Includes new page for data visualization under data generation to collect brainstorming ideas. May potentially include:
- common approaches for data visualization (R, python, excel, tableau)
- common packages for R/python, and links to those sections in scientific computing
- links to popular books and other resources (eventually fh.io class)

Also may eventually include more about statistics and exploratory data analysis!

Link to Center for Data Viz, and what they do

### CODE REVIEW

**Comment by vortexing** [comment]
This should be a draft PR right?

**Comment by vortexing** [comment]
I added this to the sidebar, so when this gets merged it will show up in the sidebar in data gen!!

**Comment by lakikowolfe** [comment]
Let me know what you all think re: links and formatting. Should I add more text for context? I thought this was pretty straightforward but I'm happy to add more.

**Comment by lakikowolfe** [comment]
@k8hertweck can you specifically review my description of the data viz center.

**Comment by vortexing** [comment]
@k8hertweck I will leave this review to you.

**Comment by vortexing** [comment]
Needs an intro paragraph and contextualization for python data viz. 
Also recommend ping'ing the R community in Slack to find a list of "Greatest Data Viz package Hits"

**Comment by k8hertweck** [comment]
I added a few sentences clarifying Center for Data Viz.

@lakikowolfe you should also include links on the software pages for R and python to point people towards these specific sections

**Comment by vortexing** [comment]
I am loosely following edits.  Remember @lakikowolfe not to use H1 in the text (so # Resources needs to be ## Resources or more).  Also, instead of bolding text, you may want to consider making them H4's or so.  They won't show up in the TOC but may be formatted better.  I forget exactly what format they get though.

**Comment by lakikowolfe** [comment]
@vortexing 

Thanks for the reminders! I'll adjust accordingly!

**Review by vortexing — APPROVED** [review]
I think we should roll this out!!  @k8hertweck ?  If you'd like to do the (merging) honors?

**Comment by vortexing** [comment]
I'm gonna do it, b/c it's great!!!

**Pull request merged**
