### PR TITLE
New information on parallel computing

### PR DESCRIPTION
**Pull request by atombaby**
Hi-

I'm opening this pull request to get some help and advice on where I'm going with this page/topic.  It won't be ready to merge for a little while, but I really wanted to get some opinions from y'all on what I've got, where I think I'm going, and if the level of detail is appropriate.

I've started with a generic introduction on parallel computing- primarily highlighting the difference between threading and distributed and will then do non-language specific discussions on specific approaches to making work run in parallel.  I'm planning on additional pages attached to this one that then implement examples of those different approaches.

I'd like to get a little more content before merging this in, so if you want to contribute, feel free to edit on this branch.

Thanks

### CODE REVIEW

**Comment by vortexing** [comment]
I think it'd be good to put a section on parallel computing in this page:
https://sciwiki.fredhutch.org/computing/cluster_rhinoGizmo/

But we should do that AFTER that pull request gets merged b/c I don't want to cross the streams unnecessarily.

**Comment by vortexing** [comment]
@atombaby and @rbarfield should we merge this in?  I can then later go back and add an introduction to it in the clusteR_rhinoGizmo file, but I'm hesitant to update from the master at this point b/c I don't want to break anything.

**Comment by atombaby** [comment]
Yes, I'd say let's merge, but I'd like to leave the branch as there's still lots of information to add.

**Comment by rbarfield** [comment]
Looks good. Sorry for the late reply.

**Pull request merged**
