### PR TITLE
Singularity docs

### PR DESCRIPTION
**Pull request by dirkpetersen**
moved and updated from old Wiki

### CODE REVIEW

**Comment by vortexing** [comment]
https://sciwiki.fredhutch.org/bioinformatics/compute_docker/

 Please add more information about when to use Singularity to this article (and link to the new demo), PRIOR to this pull request being merged.

**Comment by dirkpetersen** [comment]
OK, i updated bioinformatics/compute_docker/

**Comment by vortexing** [comment]
@dirkpetersen  you overwrote/removed my edits.  You're welcome to go back and get all of my formatting updates to your demo markdown FIRST then we can review and merge this pull request.

**Comment by dirkpetersen** [comment]
Oh, sorry I just re-applied your changes (I hope)

**Pull request merged**
