### PR TITLE
Splitting out contribution guidelines from README

### PR DESCRIPTION
**Pull request by Chilliwack**
closes out #401

### CODE REVIEW

**Comment by k8hertweck** [comment]
We really need to work on your titles, Justin

**Comment by vortexing** [comment]
I'm real mixed on this issue.  I fully support the effort to make it more clear and easier to contribute, but don't understand why it has to be on a less findable page.  Yes, contributing.md is a community standard for software-containing repo's, but that is not what this is so I'm not sure that standard makes sense.  I wish github would let us define which page we want rendered when you go to the main github repo link.  :(

**Comment by Chilliwack** [comment]
_I wish github would let us define which page we want rendered when you go to the main github repo link. :(_

thats exactly what I was hoping wikis would allow us but didnt come across doc that said that. Let me dig around some more bc I thought I did at one point read somewhere where you CAN dictate which page you render on your repo

**Comment by Chilliwack** [comment]
no go on the "I wish github would let us define which page we want rendered when you go to the main github repo link. :(" outside of just editing the readme to what you want rendered. Most ppl just use links at the top of the readme to redirect ppl so thats what I did and just added a link to contributing.md and the about page at the top of the edited readme

**Comment by Chilliwack** [comment]
tweaked some lines to address "Attempt to clean, streamline and better curate the wiki README #399"

**Pull request closed without merging**
