### PR TITLE
Python IDEs

### PR DESCRIPTION
**Pull request by vortexing**
I took a first pass at copy/paste to fix up the Python page.  I think it'd be great to get input from @kmayerb and @zyd14 initially to begin to better organize and curate the material to make it flow a bit better, maybe that means make it more article than demo (I'm assuming your original repo's will still exist, this is just an article-form version).  Once that is done, if you guys wouldn't mind deciding on how to handle your images that are remaining in the text into the right assets location in the Wiki repo (assets/python/) or good links to yours?  

Then we can open it up to a real PR instead of a draft and get some other people's thoughts on it.  Sound ok?

### CODE REVIEW

**Comment by vortexing** [comment]
Closes #502

**Comment by vortexing** [comment]
So what do you guys think?  Should we merge this in and see how it looks all rendered and decide if we should be breaking it up into IDE Resource Library entries for each IDE and then leave the intro material in this article or not?  @zyd14 @kmayerb   I will defer to you guys on this.

**Comment by vortexing** [comment]
I guess I mean too that I think that sort of structure is likely what @zyd14  was going for in this other branch: https://github.com/FredHutch/wiki/blob/enhance/software_python_szr/_scicomputing/software_python.md

Except instead of linking out to your repos for ALL the details, I'd like at least most of the details to live in the Wiki somewhere (either in this page OR in separate pages in _compdemos), so that if you delete your repo, the content still exists here).

**Comment by zyd14** [comment]
@vortexing - I think seeing it rendered together in one page would be nice... if it ends up looking like too much for a single page we could break it up as you advised.  It'd be nice to avoid making people jump around too much if it's not necessary.

**Comment by vortexing** [comment]
Sounds good.  It's always harder to get the content CREATED and not duplicated FIRST, and then if we want to parse it out a bit, that's fine.  I mean ,people can scroll and there's a TOC, so rather than making them hunt, this seems like a good starting point.

**Comment by vortexing** [comment]
I won't delete the branch yet until we know for sure what we are doing.  It should be live now (or in a few minutes).

**Comment by zyd14** [comment]
Not sure why the images are being displayed when you view it on github but not on the webpage... I'll look into it and fix it up

**Pull request merged**
