### PR TITLE
Software Development overview

### PR DESCRIPTION
**Pull request by k8hertweck**
will address #348

### CODE REVIEW

**Comment by vortexing** [comment]
Yeah, I forgot this PR was still here.  I will hang out and wait until you're done.  ;)

**Comment by vortexing** [comment]
Is this no longer a draft PR?  Do you want a review NOW? I can take care of that if so!

**Comment by k8hertweck** [comment]
I still need to finish the templates and examples section; it's tricky because there are things happening in the other repos that need to be resolved, too. The link dumps for those pages are not really optimal and what I had intended to finish. 

That being said, I don't want to hold up progress on the reworking of the section.

**Comment by vortexing** [comment]
@k8hertweck I propose we merge this in now and leave the branch for more edits.  There are a variety of changes in master that will impact our future changes we make in this effort and I think it'd be easier to see them in the rendered site.  I deleted no content, only moved it, so nothing is gone if we merge this in, just reorg'd.

**Pull request merged**
