### PR TITLE
Caisis/HDC Data Request process

### PR DESCRIPTION
**Pull request by vortexing**
This branch needs to be addressed.  There was some discussion outside of GitHub but it highlighted some issues and some guidance from those who are owning this process would be great as it doesn't seem to be documented elsewhere in an accessible place.  If it IS documented elsewhere, someone please put in the link!!

Issues appear to still include:
- What information is provided on the submission form only that if a requester forgets, they need to be reminded of (could that content live in SciWiki if it doesn't already have a home, in which case put in the link)?
- What are the modes of RECEIVING data that has identifiers in it, and how are future updates to that data handled (e.g., if more patients participate in a study then more up to date data would be desired on an ongoing basis)?
- What guidance is there for when MRNs need to be sent by a requester (how should this be done?!?!?!)?

Other thoughts @TimMonahan and @Rachierizz  and @esilgard ?  Y'all do this thing.

### CODE REVIEW

**Comment by vortexing** [comment]
Addresses (hopefully) issue #133

**Comment by TimMonahan** [comment]
re: the issues noted above by vortexing...
'Info on submission form' is it possible to return a pdf of the submission to the requester? Something like that would be easy for the requester to save and refer to later.
'Modes of receiving' in another system I have the ability to use R and connect directly to the server and get data from a sql view. This method seems to prevent any proliferation of files and leaves me more in control how current the data is.
'guidance for sending MRNs' having a common folder available to users (and a link to the folder sent to the requester) seems the best solution to this and also a good optional solution to the previous issue as well. idk. That is my 2 cents.

**Comment by sgglick** [comment]
Question: 'Info on submission form' is it possible to return a pdf of the submission to the requester? Something like that would be easy for the requester to save and refer to later. Yes, REDCap has a way to capture a completed submission in PDF.  I could add a question asking if the requester would like to receive such PDF, and then I can manually send it.  Will check REDCap to see if there is an automated response which can include such a PDF.
Question: Modes of receiving a file.  Ok, working on this. I think the ability for HDC to direct extracted data directly to a server is a great idea.  I have to talk to the engineers.  HDC has embarked on a longer tem solution for sharing data; how to improve the release the responses to a data request in the near future is something we can work on. 
MRN lists transfer from requester to HDC - the submission process now keeps the MRN listing within the automated process for completing the request.  An alternative shared folder with access via a link, which can be placed in the submission form will strongly be considered.  Thanks for the 2 cents.

**Comment by vortexing** [comment]
(If you guys comment that this is ok, then I will use Admin Privileges to get it merged!!)

**Comment by vortexing** [comment]
Addresses issue #133

**Pull request merged**
