### PR TITLE
Update access_credentials.md

### PR DESCRIPTION
**Pull request by chrisequalsdev**
Added section on configuring aws creds

### CODE REVIEW

**Comment by dtenenba** [comment]
I generally just hit enter for the `Default output format` question. I think json is a little less user friendly for most uses and it may not be what people expect if they have used the aws cli before. You can always run a command with `aws --output json ...` .

Anyway I suggest just picking the default (hitting enter) for `Default output format`.

**Comment by chrisequalsdev** [comment]
> I generally just hit enter for the `Default output format` question. I think json is a little less user friendly for most uses and it may not be what people expect if they have used the aws cli before. You can always run a command with `aws --output json ...` .
> 
> Anyway I suggest just picking the default (hitting enter) for `Default output format`.

I do the same thing so I took it out. Although apparently if you do that, it [defaults to json](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-format).

**Comment by dtenenba** [comment]
Yeah, that's weird because most common operations our users do (like `aws s3 ls`). do not produce JSON output.

But for the ones that do, json is the default output format. :/

**Comment by dtenenba** [comment]
One other thing, sorry - bucket names have only dashes in them, no underscores. So:

fh-pi-lastname-f-eco
not
fh-pi-lastname_f-eco

**Comment by chrisequalsdev** [comment]
> One other thing, sorry - bucket names have only dashes in them, no underscores. So:
> 
> fh-pi-lastname-f-eco not fh-pi-lastname_f-eco

Whoops, ok I put the dashes back

**Review by dtenenba — APPROVED** [review]
LGTM

**Pull request merged**
