### PR TITLE
Reworking "Common Languages" and adding "Beginner FAQ"

### LINKED ISSUE #381: Mention proprietary data analysis software
**Proposed Domain**
Scientific Computing, add to [common languages](https://sciwiki.fredhutch.org/scicomputing/software_languages/), or perhaps elsewhere? Include a separate page? Languages/software includes:
- SAS
- SPSS
- Stata
- Tableau
- MATLAB

**Content Summary**
Separate page should aggregate resources for SAS to R conversion; please add any tools, etc that would be useful in the comments below.

**Local Content Expert(s)**
I know R and am happy to help write content; I need some input from SAS folks too though!

### PR DESCRIPTION
**Pull request by k8hertweck**
Resolves #381

### CODE REVIEW

**Comment by vortexing** [comment]
I will delete it form this branch too.  I deleted Gemfile.lock in order to eliminate the security warning.   I believe that file is only needed when built locally but someone can correct me if I'm wrong.

**Comment by vortexing** [comment]
I checked before I deleted it.  Github pages does not look for the file and from what I can tell the sit is still building correctly, BUT when it's built locally it might be used.

**Comment by k8hertweck** [comment]
I found this article that is pretty good; I'll add it: https://medium.com/@data_driven/python-vs-r-for-data-science-and-the-winner-is-3ebb1a968197

**Comment by dtenenba** [comment]
Thanks for checking. I think Gemfile lock is generated when it does not exist so hopefully that will help with local builds.

**Comment by k8hertweck** [comment]
Cool. I'm going to merge and hope things don't break. I'm also going to save the donkey butter convo for Slack.

**Pull request merged**
