### PR TITLE
Proteomics

### PR DESCRIPTION
**Pull request by jdberndt**
this is far from done but I don't want it to get too far behind while I'm away on vacation. When I come back I'll have someone with domain knowledge review it because I'm pretty sure I don't know what I'm talking about.

### CODE REVIEW

**Comment by vortexing** [comment]
@jdberndt Do you think you can polish this as is enough to pull it in and have it  be a stem for a future person to come in and add more detail to?  I'm not qualified to review what you wrote. ;)

**Comment by jdberndt** [comment]
Yes, I should have some time to work on it next week. I'll also try to find someone to review it. If you want to review it for grammar, I think it's fine to merge for now.

**Comment by jdberndt** [comment]
@vortexing @ptvan Any chance that one of you can review this for grammar and merge it? I want to chat with some Proteomics folks next week and it would be nice for them to see this as on the Wiki even though it's a stub.

**Comment by vortexing** [comment]
Made some small formatting edits.  Will merge this in now so you can get feedback!!  Thanks much!!

**Pull request merged**
