### PR TITLE
updated cluster software getting started guide

### PR DESCRIPTION
**Pull request by bmcgough**

### CODE REVIEW

**Comment by vortexing** [comment]
Do you want to put a mailto in here?  Are we ready for that spam?  I was opting for putting fred hutch usernames in `username` to avoid spam b/c the audience is really meant to be mostly fred hutch oriented people who know the domain.   Thoughts?  Whatever you think is ok, let's do that and I will go update the Style Guide and also other references to sciwiki.

**Comment by bmcgough** [comment]
No, good point. I don't always think of the public nature of this.

We should link to SciComp's Centernet page, and we will try to get this updated with ticketing info, software requests, and some of our other resources.

Our page on centernet is not ready for higher visibility. We have many things to change as we transition over to the SciWiki. I'm going to see if I can crash the AEM training this afternoon so I can try to fix these things myself.

Thanks,

Ben McGough
System Administrator / Center IT - Scientific Computing / 206.667.7818
SciComp Office Hours: Wed. 10-noon M2-B102
SciComp Cloud Consulting: Tue. 3pm Thomas D3-106
bmcgough@fredhutch.org / Fred Hutch / Cures Start Here

----- Original Message -----

**Comment by vortexing** [comment]
I do love the irony of your comment about how we shouldn't put a mailto in the site actually has your email signature in it WITH your email address included.  :)

I will edit to reflect that.

**Comment by vortexing** [comment]
@bmcgough can you resolve the conflicts in this branch so we can merge your pull request?

**Pull request merged**
