### PR TITLE
Add announcement for maintenance

### PR DESCRIPTION
**Pull request by atombaby**
Announcement for the october maintenance work

### CODE REVIEW

**Comment by chrisequalsdev** [comment]
I like it. We're also updating some OS packages too? That might be user impacting and worth mentioning.

**Comment by fh-hazel** [comment]
It looks good to me. When I did a dist-upgrade dry run almost all the packages that would be installed or updated  were kernel and nvidia related. There are a few others as well, but I don't know to what extent they might affect the users.

`The following NEW packages will be installed:
  efibootmgr linux-headers-4.15.0-213 linux-headers-4.15.0-213-generic linux-image-4.15.0-213-generic linux-modules-4.15.0-213-generic linux-modules-extra-4.15.0-213-generic ubuntu-advantage-desktop-daemon
The following packages will be upgraded:
  apt apt-transport-https apt-utils distro-info-data fwupd fwupd-signed grub-common grub-pc grub-pc-bin grub2-common iptables libapt-inst2.0 libapt-pkg5.0 libfwupd2 libip4tc0 libip6tc0 libiptc0 libnvidia-cfg1-460 libnvidia-cfg1-470 libnvidia-common-460
  libnvidia-common-470 libnvidia-compute-460 libnvidia-compute-470 libnvidia-decode-460 libnvidia-decode-470 libnvidia-encode-460 libnvidia-encode-470 libnvidia-extra-460 libnvidia-extra-470 libnvidia-fbc1-460 libnvidia-fbc1-470 libnvidia-gl-460
  libnvidia-gl-470 libnvidia-ifr1-460 libnvidia-ifr1-470 libodbc1 libsmbclient libunwind8 libwbclient0 libxtables12 linux-generic linux-headers-generic linux-image-generic msodbcsql17 nvidia-compute-utils-460 nvidia-compute-utils-470 nvidia-dkms-460
  nvidia-dkms-470 nvidia-driver-460 nvidia-driver-470 nvidia-kernel-common-460 nvidia-kernel-common-470 nvidia-kernel-source-460 nvidia-kernel-source-470 nvidia-utils-460 nvidia-utils-470 odbcinst odbcinst1debian2 python-apt-common python-samba python3-apt
  python3-software-properties samba-common samba-common-bin samba-libs smbclient software-properties-common software-properties-gtk tcpdump ubuntu-advantage-tools unixodbc update-notifier update-notifier-common xserver-xorg-video-nvidia-460
  xserver-xorg-video-nvidia-470`

**Comment by atombaby** [comment]
> We're also updating some OS packages too?

Theoretically those are all upgraded in the background by unattended-updates, but I can put some words in there about that.

**Comment by atombaby** [comment]
> I don't know to what extent they might affect the users

I think most of that is sufficiently "behind the scenes" that nobody's going to notice.  The python stuff would be the only thing I'd worry about, but since we use modules it shouldn't be a problem.

I'm going to go ahead and merge- we can still update this doc over time.

**Comment by dtenenba** [comment]
Should we maybe put "2023" in there somewhere in case people come across that page and wonder if it's maintenance that already happened or hasn't happened yet?

**Pull request merged**
