### PR TITLE
Refactor of scicomp landing page

### PR DESCRIPTION
**Pull request by atombaby**
Getting started on #130.  The landing page has been changed to`_computing/scicomp_overview.md` and the contents redone from `cluster_overview.md`.  The hope is to make a bit more of a narrative flow between sections and add more detail about what the reader will find at the link.  This should allow readers to quickly jump to the area of interest.

### CODE REVIEW

**Comment by bmcgough** [comment]
I think that comp_index _itself_ should be the SciComp overview, and not an additional page. What do you think?

I'm in to fewer pages.

**Comment by atombaby** [comment]
I think I thought this was the sidebar.

**Comment by vortexing** [comment]
hmmmm, I too am confused. 

comp_index is the first landing page you come to when you click on Computing.  This should have an overview of each of your main sections (Access and Credentials/Storage/Scicomputing/Software, Resources, Updates).

THEN within each of those four sections, you have a {section}_overview page that should be the overview for the section only.  Then each page in the section is its own markdown with {section} in front of it.

**Comment by vortexing** [comment]
It might perhaps be best to write this out, decide on names for your sections, update the file names so they make sense {section}_overview, {section}_topic1, and then stop changing names.  I see a lot of evolution and name changes and that really makes git/jekyll/Amy confused.

**Comment by bmcgough** [comment]
We will talk about this tomorrow at our meeting and try to come to agreement on the overview page, and sub sections.

**Comment by atombaby** [comment]
We're working on a different approach.

**Pull request closed without merging**
