### PR TITLE
Economy Local tune up

### PR DESCRIPTION
**Pull request by vortexing**
@scottsisco Will you fix this??

### CODE REVIEW

**Comment by vortexing** [comment]
@bmcgough  I have added additional edits to this page: 
https://sciwiki.fredhutch.org/compdemos/Economy-local-large/

In this branch.  @iankirkman and I would love help with tuning up several pages related to Economy Local in this pull request.

**Comment by vortexing** [comment]
I'm skipping the review process for tgis because I reopened the pull request and now it won't let ME review it.  But it's fine!!!  Thansk @iankirkman for the stealth attack here.

**Comment by reickhof** [comment]
Remove me from this thread.

On May 31, 2019, at 4:28 PM, Amy Paguirigan <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #321<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_FredHutch_wiki_pull_321&d=DwMCaQ&c=eRAMFD45gAfqt84VtBcfhQ&r=Kvusg7QdH8fnuVyjniU4yf0thk5Nelnx-9J5OhvU_3E&m=BcfUZOGVmN59bIizsj0gNBowpYh2KWCqiBEIypdwMZo&s=vYg0CTwLwOtNw98YTwzt9f3olm4y4pyl2D5mURnOSLM&e=> into master.

**Comment by brborate** [comment]
It seems I need to be removed from this thread too.

**Comment by vortexing** [comment]
It's not an email thread - it's a github pull request. You have to set your settings for github notifications for yourself.  https://help.github.com/en/articles/watching-and-unwatching-team-discussions

Also if this continues then perhaps our previous plan for having the allfredhutch team be the reviewers for the Wiki will not work b/c github is SO CHATTY.   Otherwise that plan is working (as we've seen with these tests).

**Comment by reickhof** [comment]
I am not even setup on github.

On May 31, 2019, at 4:33 PM, Amy Paguirigan <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not an email thread - it's a github pull request. You have to set your settings for github notifications for yourself. https://help.github.com/en/articles/watching-and-unwatching-team-discussions<https://urldefense.proofpoint.com/v2/url?u=https-3A__help.github.com_en_articles_watching-2Dand-2Dunwatching-2Dteam-2Ddiscussions&d=DwMCaQ&c=eRAMFD45gAfqt84VtBcfhQ&r=Kvusg7QdH8fnuVyjniU4yf0thk5Nelnx-9J5OhvU_3E&m=Uk_nT-ASbNNiT80HAck_y162tyzArqqXb_3u5SgtgzM&s=stQtfGEi5tlO8IFO3SfTgNDFtha1W1yWkfSEh667GnM&e=>

Also if this continues then perhaps our previous plan for having the allfredhutch team be the reviewers for the Wiki will not work b/c github is SO CHATTY. Otherwise that plan is working (as we've seen with these tests).

**Comment by clbennet** [comment]
Please remove me as well

**Comment by vortexing** [comment]
Well, SOMEONE got you a github account!!!!  ;) Perhaps THAT's your issue. ;)

**Comment by tlbello17** [comment]
If there was a setting changed earlier today regarding the allfredhutch
team or the Wiki, please revert this. It seems that every Fred Hutch
affiliated GitHub user is now receiving email updates for this thread, when
previously I can say at least I never received any emails, not even for the
Git repositories I actively manage.

*Thomas Bello*
PhD Candidate, Gujral Lab
tommylbello@gmail.com
tlbello@uw.edu

**Comment by reickhof** [comment]
So all of a sudden on Friday afternoon i start getting emails from github after 16 years here. It seems i am not only one.

On May 31, 2019, at 4:39 PM, Amy Paguirigan <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, SOMEONE got you a github account!!!! ;) Perhaps THAT's your issue. ;)

**Comment by tkluge1** [comment]
It would be great if I could be removed as well

Tom Kluge | 206.667.1743 | tkluge@fredhutch.org<mailto:tkluge@fredhutch.org> | HDC Product Management | Fred Hutch

**Pull request merged**
